apiVersion: v1
kind: Service
metadata:
  name: wa-timescaledb
  namespace: lissa-fit
  labels:
    app: wa-timescaledb
spec:
  type: ClusterIP
  selector:
    app: wa-timescaledb
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres